package magento

import io.gatling.core.Predef._
import io.gatling.http.Predef._
import io.gatling.jdbc.Predef._
import io.gatling.http.Headers.Names._
import scala.concurrent.duration._
import bootstrap._
import assertions._
import Headers._

object AnonymousCheckoutScenario {

    val homepage =
        exec(http("Get Homepage")
                .get("/")
                .headers(headers_1)
            )
        .pause(2)

    val category =
        exec(http("Get Catalog Page")
            .get("/furniture/living-room.html")
            .headers(headers_1)
        )
        .pause(2)

    val product =
        exec(http("Get Product Page")
            .get("/furniture/living-room/ottoman.html")
            .headers(headers_1)
            .check(
                css("#product_addtocart_form input[name='form_key']","value")
                .saveAs("form_key")
            )
        )
        .exec(http("Add To Cart")
          .post("/checkout/cart/add/uenc/aHR0cDovLzEyNy4wLjAuMS9tYWdlbnRvLWdpdC1jbG9uZS9mdXJuaXR1cmUvbGl2aW5nLXJvb20vb3R0b21hbi5odG1sP19fX1NJRD1V/product/51/form_key/${form_key}/")
          .headers(headers_73)
            .param("""form_key""","""${form_key}""")
            .param("""product""", """51""")
            .param("""related_product""", """""")
            .param("""qty""", """1""")
        )
        .pause(1)

    var checkout = 
        exec(http("Proceed to Checkout")
            .get("/checkout/onepage/")
            .headers(headers_checkout_onepage)
            .check(status.is(200))
        )
        .pause(1)
        .exec(http("Checkout as Guest")
            .post("/checkout/onepage/saveMethod/")
            .headers(headers_savemethod)
            .param("""method""", """guest""")
            .check(status.is(200))
        )
        .exec(http("Load Billing")
            .get("/checkout/onepage/progress/")
            .headers(headers_getbilling)
            .queryParam("""toStep""", """billing""")
        )
        .pause(4)
        .feed(csv("magento_buyers.csv").queue)
        .exec(http("Submit Billing")
            .post("/checkout/onepage/saveBilling/")
            .headers(headers_savebilling)
                .param("""billing[address_id]""", """""")
                .param("""billing[firstname]""", """Test""")
                .param("""billing[lastname]""", "${Lastname}")
                .param("""billing[company]""", """""")
                .param("""billing[email]""", "${Email}")
                .param("""billing[street][]""", """123 Any St""")
                .param("""billing[street][]""", """""")
                .param("""billing[city]""", """Dearborn""")
                .param("""billing[region_id]""", """33""")
                .param("""billing[region]""", """""")
                .param("""billing[postcode]""", """48124""")
                .param("""billing[country_id]""", """US""")
                .param("""billing[telephone]""", """734-555-1234""")
                .param("""billing[fax]""", """""")
                .param("""billing[customer_password]""", """""")
                .param("""billing[confirm_password]""", """""")
                .param("""billing[save_in_address_book]""", """1""")
                .param("""billing[use_for_shipping]""", """1""")
            .check(status.is(200))
        )
        .exec(http("Load Shipping")
            .get("/checkout/onepage/progress/")
            .headers(headers_getshipping)
            .queryParam("""toStep""", """shipping_method""")
        )
        .exec(http("Submit Shipping")
            .post("/checkout/onepage/saveShippingMethod/")
            .headers(headers_saveshipping)
                .param("""shipping_method""", """flatrate_flatrate""")
                .param("""giftoptions[7][type]""", """quote""")
                .param("""giftoptions[10][type]""", """quote_item""")
        )
        .exec(http("Load Payment")
            .get("/checkout/onepage/progress/")
            .headers(headers_getpayment)
            .queryParam("""toStep""", """payment""")
        )
        .exec(http("Submit Payment")
            .post("/checkout/onepage/savePayment/")
            .headers(headers_savepayment)
                .param("""payment[method]""", """checkmo""")
        )
        .exec(http("Load Review")
            .get("/checkout/onepage/progress/")
            .headers(headers_getreview)
            .queryParam("""toStep""", """review""")
        )
        .exec(http("Submit Order")
            .post("/checkout/onepage/saveOrder/")
            .headers(headers_savereview)
                .param("""payment[method]""", """checkmo""")
        )
        .exec(http("Load Success")
            .get("/checkout/onepage/success/")
            .headers(headers_1)
        )
        .exec(http("Get Homepage 2")
          .get("/")
          .headers(headers_1)
        )

    val scn = scenario("Anonymous Browser")
        .exec( homepage, category, product, checkout)
        
}